Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
nba_data.loc[['Mitchell Butler','JaKarr Sampson','Malik Sealy']]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[24], line 1[0m
[0;32m----> 1[0m [43mnba_data[49m[38;5;241;43m.[39;49m[43mloc[49m[43m[[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mMitchell Butler[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mJaKarr Sampson[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mMalik Sealy[39;49m[38;5;124;43m'[39;49m[43m][49m[43m][49m

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pandas/core/indexing.py:1073[0m, in [0;36m_LocationIndexer.__getitem__[0;34m(self, key)[0m
[1;32m   1070[0m axis [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39maxis [38;5;129;01mor[39;00m [38;5;241m0[39m
[1;32m   1072[0m maybe_callable [38;5;241m=[39m com[38;5;241m.[39mapply_if_callable(key, [38;5;28mself[39m[38;5;241m.[39mobj)
[0;32m-> 1073[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_getitem_axis[49m[43m([49m[43mmaybe_callable[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxis[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pandas/core/indexing.py:1301[0m, in [0;36m_LocIndexer._getitem_axis[0;34m(self, key, axis)[0m
[1;32m   1298[0m     [38;5;28;01mif[39;00m [38;5;28mhasattr[39m(key, [38;5;124m"[39m[38;5;124mndim[39m[38;5;124m"[39m) [38;5;129;01mand[39;00m key[38;5;241m.[39mndim [38;5;241m>[39m [38;5;241m1[39m:
[1;32m   1299[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mCannot index with multidimensional key[39m[38;5;124m"[39m)
[0;32m-> 1301[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_getitem_iterable[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxis[49m[43m)[49m
[1;32m   1303[0m [38;5;66;03m# nested tuple slicing[39;00m
[1;32m   1304[0m [38;5;28;01mif[39;00m is_nested_tuple(key, labels):

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pandas/core/indexing.py:1239[0m, in [0;36m_LocIndexer._getitem_iterable[0;34m(self, key, axis)[0m
[1;32m   1236[0m [38;5;28mself[39m[38;5;241m.[39m_validate_key(key, axis)
[1;32m   1238[0m [38;5;66;03m# A collection of keys[39;00m
[0;32m-> 1239[0m keyarr, indexer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_get_listlike_indexer[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[43maxis[49m[43m)[49m
[1;32m   1240[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39m_reindex_with_indexers(
[1;32m   1241[0m     {axis: [keyarr, indexer]}, copy[38;5;241m=[39m[38;5;28;01mTrue[39;00m, allow_dups[38;5;241m=[39m[38;5;28;01mTrue[39;00m
[1;32m   1242[0m )

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pandas/core/indexing.py:1432[0m, in [0;36m_LocIndexer._get_listlike_indexer[0;34m(self, key, axis)[0m
[1;32m   1429[0m ax [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39m_get_axis(axis)
[1;32m   1430[0m axis_name [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39m_get_axis_name(axis)
[0;32m-> 1432[0m keyarr, indexer [38;5;241m=[39m [43max[49m[38;5;241;43m.[39;49m[43m_get_indexer_strict[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[43maxis_name[49m[43m)[49m
[1;32m   1434[0m [38;5;28;01mreturn[39;00m keyarr, indexer

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pandas/core/indexes/base.py:6113[0m, in [0;36mIndex._get_indexer_strict[0;34m(self, key, axis_name)[0m
[1;32m   6110[0m [38;5;28;01melse[39;00m:
[1;32m   6111[0m     keyarr, indexer, new_indexer [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_reindex_non_unique(keyarr)
[0;32m-> 6113[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_raise_if_missing[49m[43m([49m[43mkeyarr[49m[43m,[49m[43m [49m[43mindexer[49m[43m,[49m[43m [49m[43maxis_name[49m[43m)[49m
[1;32m   6115[0m keyarr [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mtake(indexer)
[1;32m   6116[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(key, Index):
[1;32m   6117[0m     [38;5;66;03m# GH 42790 - Preserve name from an Index[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pandas/core/indexes/base.py:6173[0m, in [0;36mIndex._raise_if_missing[0;34m(self, key, indexer, axis_name)[0m
[1;32m   6171[0m     [38;5;28;01mif[39;00m use_interval_msg:
[1;32m   6172[0m         key [38;5;241m=[39m [38;5;28mlist[39m(key)
[0;32m-> 6173[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNone of [[39m[38;5;132;01m{[39;00mkey[38;5;132;01m}[39;00m[38;5;124m] are in the [[39m[38;5;132;01m{[39;00maxis_name[38;5;132;01m}[39;00m[38;5;124m][39m[38;5;124m"[39m)
[1;32m   6175[0m not_found [38;5;241m=[39m [38;5;28mlist[39m(ensure_index(key)[missing_mask[38;5;241m.[39mnonzero()[[38;5;241m0[39m]][38;5;241m.[39munique())
[1;32m   6176[0m [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mnot_found[38;5;132;01m}[39;00m[38;5;124m not in index[39m[38;5;124m"[39m)

[0;31mKeyError[0m: "None of [Index(['Mitchell Butler', 'JaKarr Sampson', 'Malik Sealy'], dtype='object')] are in the [index]"
KeyError: "None of [Index(['Mitchell Butler', 'JaKarr Sampson', 'Malik Sealy'], dtype='object')] are in the [index]"

